[book]
authors = ["Bytecode Alliance"]
language = "en"
multilingual = false
src = "src"
title = "The WebAssembly Component Model"

[output.html]
git-repository-url = "https://github.com/bytecodealliance/component-docs/tree/main/component-model"
edit-url-template = "https://github.com/bytecodealliance/component-docs/tree/main/component-model/{path}"
additional-css = ["theme/head.hbs"]

[preprocessor.alerts]

[output.linkcheck]
